title: 湿湿娘V4 | 周刊页 

description: >
    湿湿娘建立于2009年10月，旨在帮助用户及时获取最新的V+歌曲。目前免费提供NICONICO网站白金会员拥有的高画质PV和同等质量MP3的在线播放和下载服务。湿湿娘网站曲库庞大，是目前国内最大的V+影音资源库。<br/>
    湿湿娘新站：<a href="http://dev.shi-shi.net" target="_blank"><strong>dev.shi-shi.net</strong></a><br/>
    本页主要提供周刊精彩PV的欣赏，更多功能请访问主站哦。<br/>
    
contact: >
    欢迎您给我们提供建议，更期待有才华的你加入我们。<br/>
    更多的资金支持，可以直接帮助我们延续这个公益项目走得更远。<br/> 
    捐助地址:donate@shi-shi.net（支付宝）<br/>
    QQ群：390734848<br/>
    官方新浪微博：@湿湿娘<br/>
    
markdown: kramdown
source:      ./
destination: ../zk
exclude: [LICENSE.txt,README.txt,node_modules,zkjosns,zktool.js]